In [1]:
import numpy as np
import pandas as pd
from pyntcloud import PyntCloud
import utils

C:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
data, labels = utils.load_h5("./modelnet40/ply_data_train0.h5")
categories = utils.get_category_names()

In [3]:
print(data[0])

[[ 0.09804384 -0.16375712 -0.88815236]
 [-0.23270538  0.20258272  0.9004929 ]
 [-0.2567441  -0.25970268 -0.49264464]
 ...
 [-0.39915243  0.11317458 -0.87155205]
 [-0.39915243  0.06148027 -0.857612  ]
 [ 0.05074174  0.04413288  0.13229933]]


In [7]:
# Load and display pickled point cloud of teapot
point_cloud = data[0]

# Setup point cloud visualization
points = pd.DataFrame(point_cloud, columns=["x", "y", "z"])
#colors = np.full((point_cloud.shape[0], 3), (1, 1, 1), dtype=np.float32)
#points[["red", "blue", "green"]] = pd.DataFrame(colors, index=points.index)

#print(points)

print(points[["x", "y", "z"]].values)

# Show point cloud
cloud = PyntCloud(points)
cloud.plot(point_size=0.01, opacity=1.0, line_color=[])

[[ 0.09804384 -0.16375712 -0.88815236]
 [-0.23270538  0.20258272  0.9004929 ]
 [-0.2567441  -0.25970268 -0.49264464]
 ...
 [-0.39915243  0.11317458 -0.87155205]
 [-0.39915243  0.06148027 -0.857612  ]
 [ 0.05074174  0.04413288  0.13229933]]


In [5]:

print(categories[label[0][0]])

NameError: name 'label' is not defined

In [ ]:
print(len(label))

In [ ]:
print(len(model))
print(len(model[0]))
print(len(model[0][0]))