In [45]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()

# Initializer to the bias to identity
def bias_identity_init(shape, dtype, partition_info):
    rows = np.sqrt(shape[0]).astype(dtype=np.int32)
    return tf.reshape(tf.eye(rows, dtype=dtype), [-1])

feat = tf.zeros((1, 3))
dense_layer = tf.layers.dense(feat,
                              units=9,
                              activation=None,
                              bias_initializer=bias_identity_init,
                              kernel_initializer=tf.zeros_initializer,
                              name="dense1")

In [46]:
# Create session
sess = tf.InteractiveSession()
tf.global_variables_initializer().run()

In [47]:
out = sess.run(dense_layer)

In [48]:
with tf.variable_scope('dense1', reuse=True):
    print(sess.run(tf.get_variable('kernel')))
    print(sess.run(tf.get_variable('bias')))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 0. 0. 0. 1. 0. 0. 0. 1.]
